### ISSUE TITLE
[SCP] Translation file is not present

### ISSUE THREAD

**Issue by LindaFelicia** [JoinedSenses/SM-Custom-ChatColors-Menu#2]
even the file already exists inside the translations folder

![A](https://user-images.githubusercontent.com/50535893/233195757-e564ed68-1867-48f3-84c0-8b94944e3429.png)
![B](https://user-images.githubusercontent.com/50535893/233195772-02f19c54-1f99-47b8-9256-39e7024ee10e.png)

**Comment by JoinedSenses** [comment]
Go to addons/sourcemod/logs and open the normal log file from today and search for text `[SCP] Loading translation file`. What is the text in the brackets [ ]? for example, in tf2 it says `[SCP] Loading translation file [scp.tf.phrases]`

**Comment by LindaFelicia** [comment]
L 04/20/2023 - 04:02:06: -------- Mapchange to bt1 --------
L 04/20/2023 - 04:02:06: [simple-chatprocessor.smx] [SCP] Recognized mod [Left 4 Dead 2].
L 04/20/2023 - 04:02:06: [simple-chatprocessor.smx] [SCP] Translation file is not present
L 04/20/2023 - 04:02:06: [SM] Exception reported: Translation file is not present
L 04/20/2023 - 04:02:06: [SM] Blaming: simple-chatprocessor.smx
L 04/20/2023 - 04:02:06: [SM] Call stack trace:
L 04/20/2023 - 04:02:06: [SM]   [0] SetFailState
L 04/20/2023 - 04:02:06: [SM]   [1] Line 173, simple-chatprocessor.sp::OnPluginStart
L 04/20/2023 - 04:02:06: [SM] Unable to load plugin "simple-chatprocessor.smx": Error detected in plugin startup (see error logs)

No search result for "[SCP] Loading translation file"

**Comment by JoinedSenses** [comment]
You are checking addons/sourcemod/logs/L20230420.log ?

**Comment by LindaFelicia** [comment]
I checked /left4dead2/console.log
in L20230420.log,the record about this plugin has only one line:
L 04/20/2023 - 04:17:13: [simple-chatprocessor.smx] [SCP] Recognized mod [Left 4 Dead 2].
That's it

**Comment by JoinedSenses** [comment]
Thanks, I see now that the logging needs to be improved. I am going to edit the code and upload here for you to try so we can see the file name it is looking for.

**Comment by JoinedSenses** [comment]
Try this SMX and then let me know what the error says. I modified the error message so it prints the name of the file it looks for.  

[simple-chatprocessor.zip](https://github.com/JoinedSenses/SM-Custom-ChatColors-Menu/files/11278012/simple-chatprocessor.zip)

**Comment by LindaFelicia** [comment]
L 04/20/2023 - 06:33:01: [simple-chatprocessor.smx] [SCP] Translation file is not present [scp.left4dead2.phrases]
L 04/20/2023 - 06:33:01: [SM] Exception reported: Translation file is not present [scp.left4dead2.phrases]

I renamed the translation file, the error has been resolved, thank you.

**Comment by JoinedSenses** [comment]
🥳🎉

**Comment by fbef0102** [comment]
```c
In l4d1: scp.l4d.phrases.txt should be scp.left4dead.phrases.txt
In l4d2: scp.l4d2.phrases.txt should be scp.left4dead2.phrases.txt
```
